# Generated by Django 3.2.6 on 2021-08-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
